### ISSUE TITLE
Use cgilua 5.2.1 so it works on Lua 5.2

### ISSUE THREAD

**Issue by xspager** [sailorproject/sailor#70]
Hi! I don't know if there is any problem running Sailor with Lua 5.2 but the cgilua, if I install the latest version of cgilua available on luarocks, the 5.2.1, it seem to work fine. So I suggest changing the rockspec. Does it make sense?

**Comment by xspager** [comment]
I think the issue openresty/lua-nginx-module#343 on lua_nginx_module means Sailor should stick with Lua 5.1 if it shouldn't be restricted to using only fastcgi with nginx. :disappointed:

**Comment by Etiene** [comment]
Yes, in theory sailor is compatible with Lua5.2 the problem is that the latest cgilua is not compatible with Lua5.1

**Comment by xspager** [comment]
Oh, I see. :tired_face:

**Comment by louis77** [comment]
Just ran into the same issue and got:

`/usr/local/share/lua/5.2/cgilua.lua:199: attempt to call upvalue 'setfenv' (a nil value)
stack traceback:
  /usr/local/share/lua/5.2/cgilua.lua:161: in function 'setfenv'
  /usr/local/share/lua/5.2/cgilua.lua:199: in function 
  (...tail calls...)
  [C]: in function 'xpcall'
  /usr/local/share/lua/5.2/cgilua.lua:169: in function 'pcall'
  /usr/local/share/lua/5.2/cgilua.lua:630: in function 'main'
  /usr/local/share/lua/5.2/wsapi/sapi.lua:53: in function 
  (...tail calls...)
  [C]: in function 'xpcall'
  /usr/local/share/lua/5.2/wsapi/common.lua:270: in function 'run_app'
  [string " local app_name, bootstrap_code, is_file = ...."]:68: in function <[string " local app_name, bootstrap_code, is_file = ...."]:65>`

Since I'm somewhat new to Lua, I thought that "Lua 5.2 compatible" actually means Lua 5.2 compatible :-) Any way to work around that issue?

**Comment by Etiene** [comment]
Try installing the latest cgilua and then installing sailor? If that doesnt
work Ill make a rockspec for you! Sorry for that, I need to document this.
The problem is that the newest cgilua isnt compatible with 5.1 and 5.1 is
the most used. But sailor is compatible with both cgiluas and both 5.1 ans
5.2. Its actually very late here but tomorrow I'll inspect the Travis CI
builds to see how I packaged it then make a guide :)
Em 29/01/2016 9:48 PM, "Louis Brauer" <notifications@github.com> escreveu:

**Comment by hishamhm** [comment]
The newest cgilua _isn't_ compatible with Lua 5.1?? This must be fixed.

**Comment by Etiene** [comment]
As far as I know, yes! I didn't look deeply into it, though. But yes, I agree it shouldn't be the case

**Comment by mpeterv** [comment]
I pushed [something](https://github.com/keplerproject/cgilua/commit/d05760f02bdf529692702a752d785890faf4adba) that _should_ be a fix but it's hard to say given there are no tests there really. But it doesn't crash now. @hishamhm a 5.2.0 release would be nice, it'd also add Lua 5.3 compat.

**Comment by Etiene** [comment]
Ok! So for now if I changed the cgilua to >= 5.1.4 it will install that one when Lua 5.1 is available and the newest one when 5.2 is available. This should help for now. But the cgilua thing should be addressed. I tested and apparently it works fine with both 5.1 and 5.2 after @mpeterv's patch but it needs a new rockspec
